<?xml version="1.0"?>
<package format="3">
  <name>ee_serial_mux</name>
  <version>0.1.0</version>
  <description>Python-based ROS 2 node for serial gripper control</description>
  <maintainer email="your@email.com">Your Name</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
