controller_manager:
  ros__parameters:
    ## publish /joint_states ------------
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ## the FollowJointTrajectory server MoveIt talks to
    scarab_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint_1_to_joint_2
        - joint_2_to_link_2
        - link_2_to_joint_3
        - joint_4_to_joint_5
        - joint_5_to_joint_6
        - joint_6_to_flange
      command_interfaces:
        - position
      state_interfaces:
        - position
