# controller_manager:
#   ros__parameters:
#     update_rate: 100
#     scarab_arm_controller:
#       type: joint_trajectory_controller/JointTrajectoryController
#       joints: [...]
#       command_interfaces: [position]
#       state_interfaces: [position]

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster