# Default initial positions for full_scrab_arm's ros2_control fake system

initial_positions:
  base_to_inner_x: 0.0
  base_to_inner_y: 0.0
  base_to_outer_x: 0.0
  base_to_outer_y: 0.0
  joint_1_to_joint_2: 0.0
  joint_2_to_link_2: 0.0
  joint_4_to_joint_5: 0.0
  joint_5_to_joint_6: 0.0
  joint_6_to_flange: 0.0
  link_2_to_joint_3: 0.0
  outer_x_to_finger_x: 0.0
  outer_y_to_finger_y: 0.0