# Default initial positions for Arm's ros2_control fake system

initial_positions:
  gripper_base to outer_link_x: 0
  gripper_base to outer_link_y: 0
  joint_1 to joint_2: 0
  joint_2 to link_2: 0
  joint_4 to joint_5: 0
  joint_5 to joint_6: 0
  joint_6 to flange: 0
  link_2 to joint_3: 0