move_group:
  ros__parameters:
    robot_description_kinematics:
      scarab_arm:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_attempts: 3
        kinematics_solver_search_resolution: 0.005   # rad
        kinematics_solver_timeout: 0.05              # s
