controller_names:
  - scarab_arm_controller

scarab_arm_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - joint_1_to_joint_2
    - joint_2_to_link_2
    - link_2_to_joint_3
    - joint_4_to_joint_5
    - joint_5_to_joint_6
    - joint_6_to_flange
