---
# src/Scarabarm/scarabarm_moveit/config/odrive_system.yaml
odrive_system:              #  <-- arbitrary node name
  ros__parameters:
    update_rate: 100
    can_interface: "can0"

    # ----- one axis (= one motor) per ODrive S1 -----
    axes:
      joint_2:              # legible key; tools don’t care what it is
        node_id: 0          # CAN-ID on the bus
        axis: 0             # 0 or 1 inside the S1
        joint_name: "joint_1_to_joint_2"
        mechanical_ratio: 64.0
        counts_per_rev: 8192
        startup_axis_state: 3        # 8 = CLOSED_LOOP_CONTROL
        input_mode: 1                # 1 = POSITION_FILTER

      joint_3:
        node_id: 1
        axis: 0
        joint_name: "joint_2_to_link_2"
        mechanical_ratio: 64.0
        counts_per_rev: 8192
        startup_axis_state: 3        # 8 = CLOSED_LOOP_CONTROL
        input_mode: 1                # 1 = POSITION_FILTER

      joint_4:
        node_id: 2
        axis: 0
        joint_name: "link_2_to_joint_3"
        mechanical_ratio: 64.0
        counts_per_rev: 8192
        startup_axis_state: 3        # 8 = CLOSED_LOOP_CONTROL
        input_mode: 1                # 1 = POSITION_FILTER

      joint_5:
        node_id: 3
        axis: 0
        joint_name: "joint_4_to_joint_5"
        mechanical_ratio: 10.0
        counts_per_rev: 8192
        startup_axis_state: 3        # 8 = CLOSED_LOOP_CONTROL
        input_mode: 1                # 1 = POSITION_FILTER

      joint_6:
        node_id: 4
        axis: 0
        joint_name: "joint_5_to_joint_6"
        mechanical_ratio: 10.0
        counts_per_rev: 8192
        startup_axis_state: 3        # 8 = CLOSED_LOOP_CONTROL
        input_mode: 1                # 1 = POSITION_FILTER
