move_group:
  ros__parameters:
    # top-level pipelines list
    planning_pipelines: ["ompl"]
    default_planning_pipeline: ompl
    planning_plugin: ompl_interface/OMPLPlanner

    ompl_planning_pipeline_config:
      planning_plugin: ompl_interface/OMPLPlanner
      planning_pipelines: ["ompl"]
      request_adapters:
        - default_planner_request_adapters/AddTimeOptimalParameterization
        - default_planner_request_adapters/FixWorkspaceBounds
        - default_planner_request_adapters/FixStartStateBounds
        - default_planner_request_adapters/FixStartStateCollision
        - default_planner_request_adapters/FixStartStatePathConstraints
