# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    scarab_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

scarab_arm_controller:
  ros__parameters:
    joints:
      - joint_1 to joint_2
      - joint_2 to link_2
      - link_2 to joint_3
      - joint_4 to joint_5
      - joint_5 to joint_6
      - joint_6 to flange
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_controller:
  ros__parameters:
    joint: gripper_base to outer_link_x