---
controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    scarab_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: forward_command_controller/ForwardCommandController

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50

scarab_arm_controller:
  ros__parameters:
    joints:
      - joint_1_to_joint_2
      - joint_2_to_link_2
      - link_2_to_joint_3
      - joint_4_to_joint_5
      - joint_5_to_joint_6
      - joint_6_to_flange
    command_interfaces: [position]
    state_interfaces: [position, velocity]

gripper_controller:
  ros__parameters:
    joints: [outer_x_to_finger_x, outer_y_to_finger_y]
    interface_name: position
