# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    scarab_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

scarab_arm_controller:
  ros__parameters:
    joints:
      - joint_1_to_joint_2
      - joint_2_to_link_2
      - link_2_to_joint_3
      - joint_4_to_joint_5
      - joint_5_to_joint_6
      - joint_6_to_flange
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
gripper_controller:
  ros__parameters:
    joint: base_to_inner_x