# initial_positions.yaml
# Default initial position for each movable joint of the scarabarm

initial_positions:
  joint_1_to_joint_2: 0.0
  joint_2_to_link_2: 0.0
  link_2_to_joint_3: 0.0
  joint_4_to_joint_5: 0.0
  joint_5_to_joint_6: 0.0
  joint_6_to_tool0: 0.0